#!/usr/bin/env python3

import numpy
import os
import enum
import sys
import json
import gzip
from Bio import SeqIO
from Bio.Seq import MutableSeq, Seq


class Strand(enum.Enum):
    POSITIVE = enum.auto()
    NEGATIVE = enum.auto()


class DnaNick:

    def __init__(self, index, strand=Strand.POSITIVE):
        self._index = index
        self._strand = strand

    def index(self):
        return self._index

    def __str__(self):
        return f"(index: {self._index})"


class SiteDamage:

    def __init__(self, index, old_char, new_char):
        self._relative_index = index
        self._old_character = old_char
        self._new_character = new_char

    def apply_to_seq(self, mutseq):
        if mutseq[self._relative_index] == self._old_character:
            mutseq[self._relative_index] = self._new_character
        else:
            raise RuntimeError(
                f"The old character ({self._old_character}) did not match the actual character ({mutseq[self._relative_index]})"
            )

    def to_dict(self):
        return {
            "index": self._relative_index,
            "old": self._old_character,
            "new": self._new_character
        }

    def __str__(self):
        return f"(index: {self._relative_index}, old: {self._old_character}, new: {self._new_character})"


class AdnaFragment:

    def __init__(self, sequence, start, end, taxa_name):
        self._start_index = start
        self._end_index = end
        self._sequence = sequence[self._start_index:self._end_index]
        self._taxa_name = taxa_name
        self._damage = []

    @property
    def taxa_name(self):
        return self._taxa_name

    @property
    def annotated_sequence_name(self):
        return self.taxa_name + "_" + str(self._start_index) + "-" + str(
            self._end_index)

    @property
    def left_overhang(self):
        return self._overhang_left_len

    @left_overhang.setter
    def left_overhang(self, length):
        if length > len(self._sequence):
            raise RuntimeError("Overhang is too long")
        self._overhang_left_len = length

    @property
    def right_overhang(self):
        return self._overhang_right_len

    @right_overhang.setter
    def right_overhang(self, length):
        if length > len(self._sequence):
            raise RuntimeError("Overhang is too long")
        self._overhang_right_len = length

    @property
    def right_overhang_start_index(self):
        return len(self) - self.right_overhang

    def __iter__(self, index):
        return self._sequence[index]

    def __len__(self):
        return len(self._sequence)

    def add_damage(self, damage):
        self._damage.append(damage)

    def _to_sequence_mut(self):
        mut_seq = MutableSeq(str(self._sequence))
        for d in self._damage:
            d.apply_to_seq(mut_seq)
        return mut_seq

    def to_sequence(self, ungap=False):
        tmp_seq = Seq(str(self._to_sequence_mut()))
        if ungap:
            tmp_seq = tmp_seq.ungap('N')
        return tmp_seq

    def to_aligned_sequence(self, sequence_length):
        mut_seq = self._to_sequence_mut()
        tmp_str = str(('N' * self._start_index) + mut_seq +
                      ('N' * (sequence_length -
                              (len(mut_seq) + self._start_index))))
        return Seq(tmp_str)

    def __str__(self):
        return f"(start: {self._start_index}, end: {self._end_index}, left overhang: {self._overhang_left_len}, right overhang: {self._overhang_right_len})"

    def add_overhang(self, overhang_length_param):
        sequence_len = len(self._sequence)
        if sequence_len == 0:
            self.left_overhang = 0
            self.right_overhang = 0
            return
        left_overhang_len = sequence_len
        right_overhang_len = sequence_len
        iters = 0

        while (left_overhang_len >= sequence_len
               or right_overhang_len >= sequence_len
               or right_overhang_len + left_overhang_len >= sequence_len):
            left_overhang_len = numpy.random.geometric(
                overhang_length_param) - 1
            right_overhang_len = numpy.random.geometric(
                overhang_length_param) - 1
            iters += 1
            if iters % 10000 == 0:
                print(
                    "We are having trouble generating overhangs for this set of parameters. Please consider changing the parameters to shorten the overhangs"
                )

        self.left_overhang = left_overhang_len
        self.right_overhang = right_overhang_len
        if (self.right_overhang + self.left_overhang) > sequence_len:
            raise RuntimeError("Overhangs cannot be longer than the fragment")

    def _roll_damage(self, index, seq_char, test_char, damage_char, rate):
        if seq_char.lower() == test_char.lower():
            if numpy.random.uniform() < rate:
                tmp_damage = SiteDamage(index, seq_char, damage_char)
                self.add_damage(tmp_damage)

    def _add_c_to_t_damage(self, single_strand_rate, double_strand_rate):
        for i, c in enumerate(self._sequence[:self.left_overhang]):
            self._roll_damage(i, c, 'C', 'T', single_strand_rate)

        for i, c in enumerate(self._sequence[self.left_overhang:],
                              start=self.left_overhang):
            self._roll_damage(i, c, 'C', 'T', double_strand_rate)

    def _add_a_to_g_damage(self, single_strand_rate, double_strand_rate):
        for i, c in enumerate(
                self._sequence[:self.right_overhang_start_index]):
            self._roll_damage(i, c, 'A', 'G', double_strand_rate)

        for i, c in enumerate(self._sequence[self.right_overhang_start_index:],
                              start=self.right_overhang_start_index):
            self._roll_damage(i, c, 'A', 'G', single_strand_rate)

    def add_deaminations(self, single_strand_rate, double_strand_rate):
        # add left overhand damage
        self._add_c_to_t_damage(single_strand_rate, double_strand_rate)
        self._add_a_to_g_damage(single_strand_rate, double_strand_rate)

    def to_dict(self):
        obj_dict = {
            "start": self._start_index,
            "end": self._end_index,
            "taxa": self._taxa_name,
            "damage": [d.to_dict() for d in self._damage],
            "overhang_l_len": self.left_overhang,
            "overhang_r_len": self.right_overhang,
        }
        return obj_dict

    def ungap(self):
        self._sequence = self._sequence.ungap()


def produce_nicks(sequence, nick_freq):
    nicks = []
    for i, _ in enumerate(sequence):
        if numpy.random.uniform() < nick_freq:
            nicks.append(DnaNick(i))
    return nicks


def produce_fragments(nicks, sequence, taxa_name):
    fragments = []
    fragments.append(AdnaFragment(sequence, 0, nicks[0].index(), taxa_name))

    for n1, n2 in zip(nicks, nicks[1:]):
        fragments.append(
            AdnaFragment(sequence, n1.index(), n2.index(), taxa_name))

    fragments.append(
        AdnaFragment(sequence, nicks[-1].index(), len(sequence), taxa_name))
    return fragments


def filter_fragments(frags, min_len=0):
    ret_frags = []
    for frag in frags:
        if len(frag) < min_len:
            continue
        if len(frag.to_sequence(ungap=True)) == 0:
            continue
        ret_frags.append(frag)

    return ret_frags


def write_frags_to_fasta_file(frags,
                              filename,
                              align,
                              ungap=False,
                              compress=True):
    fastafile = None
    if compress:
        filename_ext = os.path.splitext(filename)[1]
        if (filename_ext == '.gz' or filename_ext == ".gzip"):
            filename += '.gz'
        fastafile = gzip.GzipFile(filename, 'a')
    else:
        fastafile = open(filename, 'a')

    for f in frags:
        taxa_line = ">" + f.annotated_sequence_name + "\n"
        sequence_line = None
        if align:
            sequence_line =\
                    str(f.to_aligned_sequence(len(sequence))) + "\n"
        else:
            sequence_line =\
                    str(f.to_sequence(ungap=ungap)) + "\n"
        if compress:
            taxa_line = taxa_line.encode('utf-8')
            sequence_line = sequence_line.encode('utf-8')

        fastafile.write(taxa_line)
        fastafile.write(sequence_line)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--fasta", type=str, required=True)
    parser.add_argument("--nick-freq", type=float, required=True)
    parser.add_argument("--overhang-parameter", type=float, required=True)
    parser.add_argument("--min-length", type=int, required=False, default=None)
    parser.add_argument("--min-fragments", type=int, required=False, default=0)

    parser.add_argument("--double-strand-deamination",
                        type=float,
                        required=True)
    parser.add_argument("--single-strand-deamination",
                        type=float,
                        required=True)

    parser.add_argument("--align", action="store_true", default=False)
    parser.add_argument("--compress", action="store_true", default=False)
    parser.add_argument("--ungap", action="store_true", default=False)
    parser.add_argument("--output", type=str, required=True)
    parser.add_argument("--log", type=str, required=True)
    parser.add_argument("--seed", type=int)
    args = parser.parse_args()

    alignment = SeqIO.parse(open(args.fasta), 'fasta')

    if os.path.exists(args.output):
        print("Output file exists, refusing to overwrite the output file")
        sys.exit(1)

    output_ext = os.path.splitext(args.output)[1].lower()
    if args.compress and not (output_ext == '.gz' or output_ext == ".gzip"):
        args.output += ".gz"

    if args.align and args.ungap:
        print(
            "Refusing to align and ungap the sequence. These flags are incompatable"
        )
        sys.exit(1)

    if not args.seed is None:
        numpy.random.default_rng(args.seed)

    with gzip.GzipFile(args.log + '.gz', 'w') as logfile:
        for sequence in alignment:
            total_fragments = 0
            while total_fragments < args.min_fragments:
                nicks = produce_nicks(sequence.seq, args.nick_freq)
                frags = produce_fragments(nicks, sequence.seq, sequence.id)
                for frag in frags:
                    frag.add_overhang(args.overhang_parameter)
                    frag.add_deaminations(args.single_strand_deamination,
                                          args.double_strand_deamination)

                frags = filter_fragments(
                    frags,
                    args.min_length if not args.min_length is None else 0)
                total_fragments += len(frags)
                write_frags_to_fasta_file(frags, args.output, args.align,
                                          args.ungap, args.compress)
                logfile.write(
                    json.dumps([f.to_dict() for f in frags],
                               default=vars).encode('utf-8'))
